/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateTripImport } from './routes/CreateTrip'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CreateTripRoute = CreateTripImport.update({
  id: '/CreateTrip',
  path: '/CreateTrip',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/CreateTrip': {
      id: '/CreateTrip'
      path: '/CreateTrip'
      fullPath: '/CreateTrip'
      preLoaderRoute: typeof CreateTripImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/CreateTrip': typeof CreateTripRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/CreateTrip': typeof CreateTripRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/CreateTrip': typeof CreateTripRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/CreateTrip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/CreateTrip'
  id: '__root__' | '/' | '/CreateTrip'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTripRoute: typeof CreateTripRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTripRoute: CreateTripRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/CreateTrip"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/CreateTrip": {
      "filePath": "CreateTrip.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
